### ISSUE TITLE
securify result: 132 possible issues

### ISSUE THREAD

**Issue by drandreaskrueger** [energywebfoundation/ew-origin#3]
Out of curiosity, I have created an [ordered concatenation](https://gist.github.com/drandreaskrueger/ae3027daa95492465f4c37940de40de7) of your 20 smart contracts, and then dumped that into https://securify.chainsecurity.com . It comes up with 132 possible issues in total.

I suggest you repeat that yourself, and go through its findings - whether anything needs to be improved.

(I am not saying that there are 132 issues in your smart contracts; securify.ch is only an automated system.)

**Comment by jbentke** [comment]
I went through them and they are automated warnings that don't hold in the context of the code.

**Comment by drandreaskrueger** [comment]
Good that you did that. 

After having done that, would you advise on using securify, or is it useless?
